- name:        "Enable web ports"
  firewalld:
    service:   "{{ item }}"
    permanent: true
    immediate: true
    state:     enabled
  loop:
    - http
    - https
  when:        ansible_facts.os_family == "RedHat"
