---
- hosts:                                 localhost
  connection:                            local
  remote_user:                           root
  environment:
    http_proxy:                          http://172.24.65.79:8080
    https_proxy:                         http://172.24.65.79:8080
  vars:
    nginx_extra_http_options:            |
      proxy_buffering    off;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Scheme $scheme;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   Host $http_host;
    nginx_extra_conf_options:            |
      worker_rlimit_nofile 65535;
    nginx_worker_processes:              "2"
    nginx_worker_connections:            "10000"
    nginx_remove_default_vhost:          true
    nginx_revproxy_sites:
        default:
          ssl:                           false
          letsencrypt:                   false

        apps-nonprod.platform.hcnet.vn:
          domains:
            - apps-nonprod.platform.hcnet.vn
            - "*.apps-nonprod.platform.hcnet.vn"
          upstreams:
            - { backend_address: 10.19.168.200, backend_port: 80 }            
          ssl:                           true
          letsencrypt:                   false
          backend_protocol:              "https"
  roles:
    - ansible-role-nginx
    - ansible-nginx-revproxy
