---
- hosts:                         localhost
  connection:                    local
  remote_user:                   root
  environment:
    http_proxy:                  http://172.24.65.79:8080
    https_proxy:                 http://172.24.65.79:8080
  vars:
    nginx_extra_http_options:    |
      proxy_buffering    off;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Scheme $scheme;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   Host $http_host;
    nginx_extra_conf_options:    |
      worker_rlimit_nofile 65535;
    nginx_worker_processes:      "2"
    nginx_worker_connections:    "10000"
    nginx_remove_default_vhost:  true
    nginx_reverse_proxy_proxies:
      - config_name:             k8s-ingress
        backend_name:            k8s-ingress
        backends:
            - 10.19.168.200
        domains:
          - "*.apps-nonprod.platform.hcnet.vn"
        balancer_config:         ip_hash;
  tasks:
  roles:
    - ansible-role-nginx
    - ansible-nginx-reverse-proxy
