---
- name:       Add authentication
  htpasswd:
    path:     "/etc/nginx/{{ item.key }}_htpasswd"
    name:     "{{ item.value.auth.login }}"
    password: "{{ item.value.auth.password }}"
  with_dict:  "{{ nginx_revproxy_sites }}"
  when:
    - item.value.auth is defined
  tags:
    - nginxrevproxy

- name:       Add Site Config
  template:
    src:      reverseproxy.conf.j2
    dest:     /etc/nginx/conf.d/{{ item.key }}.conf
    owner:    root
    group:    root
  with_dict:  "{{ nginx_revproxy_sites }}"
  register:
    siteconfig
  notify:     Reload Nginx
  when:
    - not item.value.ssl | default(True)
    - not item.value.letsencrypt | default(True)
  tags:
    - nginxrevproxy

- name:       Add Https Site Config
  template:
    src:      reverseproxy_ssl.conf.j2
    dest:     /etc/nginx/conf.d/{{ item.key }}.conf
    owner:    root
    group:    root
  with_dict:  "{{ nginx_revproxy_sites }}"
  register:
    siteconfig
  notify:     Reload Nginx
  when:
    - item.value.ssl | default(False)
    - not item.value.letsencrypt | default(True)
  tags:
    - nginxrevproxy

- name:       Add Https Site key
  template:
    src:      hcvn.key
    dest:     /etc/ssl/private/hcvn.key
    owner:    root
    group:    root
  with_dict:  "{{ nginx_revproxy_sites }}"
  when:
    - siteconfig is success
    - item.value.ssl | default(False)
    - not item.value.letsencrypt | default(True)
  tags:
    - nginxrevproxy

- name:       Add Https Site cert
  template:
    src:      hcvn.pem
    dest:     /etc/ssl/private/hcvn.pem
    owner:    root
    group:    root
  with_dict:  "{{ nginx_revproxy_sites }}"
  when:
    - siteconfig is success
    - item.value.ssl | default(False)
    - not item.value.letsencrypt | default(True)
  tags:
    - nginxrevproxy

- name:       Create WebRoot sites
  file:
    dest:     /var/www/{{ item.key }}/.well-known
    mode:     0775
    state:    directory
    owner:    nginx
    group:    nginx
  with_dict:  "{{ nginx_revproxy_sites }}"
  when:
    - siteconfig is success
  tags:
    - nginxrevproxy

- name:       WebRoot Permissions Sites
  file:
    dest:     /var/www/{{ item.key }}
    mode:     0775
    state:    directory
    owner:    nginx
    group:    nginx
    recurse:  true
  with_dict:  "{{ nginx_revproxy_sites }}"
  when:
    - siteconfig is success
  tags:
    - nginxrevproxy

- include_tasks: letsencrypt.yml
  tags:
    - lesencrypt
    - nginxrevproxy
