---
# https://github.com/ansible/ansible/issues/22171
- name: restart auditd
  become: 'yes'
  become_method: sudo
  command: service auditd restart
  ignore_errors: true
  args:
    warn: false

- name: generate auditd
  become: 'yes'
  become_method: sudo
  command: augenrules

- name: restart sysctl
  become: 'yes'
  become_method: sudo
  service:
    name: systemd-sysctl
    state: restarted

- name: reload systemd
  become: 'yes'
  become_method: sudo
  systemd:
    daemon_reload: 'yes'

- name: rkhunter propupd
  become: 'yes'
  become_method: sudo
  command: rkhunter --propupd

- name: enable aidecheck
  become: 'yes'
  become_method: sudo
  systemd:
    name: aidecheck.timer
    enabled: 'yes'
    state: started

- name: disable aidecheck
  become: 'yes'
  become_method: sudo
  systemd:
    name: aidecheck.timer
    state: stopped
    enabled: 'no'

- name: mask aidecheck
  become: 'yes'
  become_method: sudo
  systemd:
    name: aidecheck.timer
    masked: 'yes'
    stated: stopped
    enabled: 'no'

- name: restart sshd
  become: 'yes'
  become_method: sudo
  service:
    name: sshd
    state: restarted

- name: apt-get autoremove
  become: 'yes'
  become_method: sudo
  apt:
    autoremove: 'yes'

- name: apt-get clean
  become: 'yes'
  become_method: sudo
  apt:
    autoclean: 'yes'

- name: mask apport
  become: 'yes'
  become_method: sudo
  systemd:
    name: apport.service
    masked: 'yes'
    enabled: 'no'
    state: stopped

- name: mask motdnews
  become: 'yes'
  become_method: sudo
  systemd:
    name: motd-news.timer
    masked: 'yes'
    enabled: 'no'
    state: stopped

- name: yum clean
  dnf:
    autoremove: 'yes'
  when: ansible_os_family == "RedHat"
  tags:
    - yum
    - packages
    - security

- name: enable haveged
  become: 'yes'
  become_method: sudo
  systemd:
    name: haveged
    enabled: 'yes'
    state: started

- name: reboot node
  become: 'yes'
  become_method: sudo
  reboot:
    pre_reboot_delay: "{{ 3600 | random(start=1) }}"
...
