---
- name: disable motd-news
  become: 'yes'
  become_method: sudo
  lineinfile:
    regexp: "^ENABLED="
    line: "ENABLED=0"
    dest: /etc/default/motd-news
    mode: 0644
    state: present
    create: 'no'
    backrefs: 'yes'
  ignore_errors: true
  notify:
    - mask motdnews
  when: ansible_os_family == "Debian"
  tags:
    - motd
    - security

- name: motd updates permissions
  become: 'yes'
  become_method: sudo
  file:
    dest: /etc/update-motd.d
    mode: 0444
    recurse: 'yes'
  ignore_errors: true
  when: ansible_os_family == "Debian"
  tags:
    - motd
    - security

- name: /etc/update-motd.d permission
  become: 'yes'
  become_method: sudo
  file:
    dest: /etc/update-motd.d
    mode: 0755
  ignore_errors: true
  when: ansible_os_family == "Debian"
  tags:
    - motd
    - security
...
